############################################################################
#
# This script processes the results of the dewy-pine projections under
# four scenarios for each covariate: 
# 
# (1) Focal = min value, other = mean
# (2) Focal = max value, other = mean
# (3) Focal = min value, other = observed value when focal is min
# (4) Focal = max value, other = observed value when focal is min
#
# Author: Eva Conquet
#
###########################################################################

###########################################################################
#
# 1. House keeping and loading libraries and data ----
#
###########################################################################

## 1.1. House keeping ----
# -------------------

setwd("/Users/esinickin/Downloads/EsinsProjections")

rm(list = ls())


## 1.2. Loading libraries ----
# -----------------------

library(ggplot2)
library(viridis)


## 1.3. Loading data ----
# ------------------

for(i in 1:length(list.files(path = "Output/", pattern = "IBM_[^N]")[grep("other", list.files(path = "Output/", pattern = "IBM_[^N]"))])){
  
  load(paste0("Output/", list.files(path = "Output/", pattern = "IBM_[^N]")[grep("other", list.files(path = "Output/", pattern = "IBM_[^N]"))])[i])
}




###########################################################################
#
# 2. Putting lambdas into a table ----
#
###########################################################################

nb_proj = nrow(ibm_vertedero_summerT_min_other_cov_mean[[1]]$log_lambda) * length(ibm_vertedero_summerT_min_other_cov_mean)
nb_years = ncol(ibm_vertedero_summerT_min_other_cov_mean[[1]]$log_lambda)

# Creating the empty table
results_df = expand.grid(population = c("Bujeo", "Prisoneros", "Retin", "MonteraTorero", "SCarbDist", 
                                        "SierraCarboneraY5", "SierraRetinY5", "Vertedero"),
                         projection = seq(1, nb_proj),
                         year = seq(1, nb_years), 
                         focal_cov = c("summerT", "prevwinterT", "fallR", "prevfallR", 
                                       "prevwinterR", "dens", "size", "TSF"),
                         focal_min_max = c("min", "max"),
                         other_mean_obs = c("mean", "obs"))


# Fill in data
unique(paste(results_df$focal_cov[which(results_df$population == "Bujeo")], 
             results_df$focal_min_max[which(results_df$population == "Bujeo")], 
             results_df$other_mean_obs[which(results_df$population == "Bujeo")]))

results_df$lambda = NA

results_df$lambda[which(results_df$population == "Bujeo")] = 
  c(c(ibm_bujeo_summerT_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_bujeo_summerT_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_bujeo_summerT_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_bujeo_summerT_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_bujeo_prevwinterT_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_bujeo_prevwinterT_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_bujeo_prevwinterT_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_bujeo_prevwinterT_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_bujeo_fallR_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_bujeo_fallR_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_bujeo_fallR_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_bujeo_fallR_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_bujeo_prevfallR_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_bujeo_prevfallR_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_bujeo_prevfallR_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_bujeo_prevfallR_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_bujeo_prevwinterR_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_bujeo_prevwinterR_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_bujeo_prevwinterR_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_bujeo_prevwinterR_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_bujeo_dens_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_bujeo_dens_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_bujeo_dens_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_bujeo_dens_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_bujeo_size_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_bujeo_size_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_bujeo_size_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_bujeo_size_min_other_cov_mean[[4]]$log_lambda),
    rep(NA, nb_proj * nb_years),
    c(ibm_bujeo_summerT_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_bujeo_summerT_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_bujeo_summerT_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_bujeo_summerT_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_bujeo_prevwinterT_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_bujeo_prevwinterT_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_bujeo_prevwinterT_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_bujeo_prevwinterT_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_bujeo_fallR_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_bujeo_fallR_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_bujeo_fallR_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_bujeo_fallR_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_bujeo_prevfallR_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_bujeo_prevfallR_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_bujeo_prevfallR_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_bujeo_prevfallR_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_bujeo_prevwinterR_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_bujeo_prevwinterR_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_bujeo_prevwinterR_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_bujeo_prevwinterR_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_bujeo_dens_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_bujeo_dens_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_bujeo_dens_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_bujeo_dens_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_bujeo_size_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_bujeo_size_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_bujeo_size_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_bujeo_size_max_other_cov_mean[[4]]$log_lambda),
    rep(NA, nb_proj * nb_years),
    c(ibm_bujeo_summerT_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_bujeo_summerT_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_bujeo_summerT_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_bujeo_summerT_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_bujeo_prevwinterT_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_bujeo_prevwinterT_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_bujeo_prevwinterT_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_bujeo_prevwinterT_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_bujeo_fallR_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_bujeo_fallR_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_bujeo_fallR_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_bujeo_fallR_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_bujeo_prevfallR_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_bujeo_prevfallR_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_bujeo_prevfallR_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_bujeo_prevfallR_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_bujeo_prevwinterR_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_bujeo_prevwinterR_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_bujeo_prevwinterR_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_bujeo_prevwinterR_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_bujeo_dens_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_bujeo_dens_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_bujeo_dens_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_bujeo_dens_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_bujeo_size_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_bujeo_size_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_bujeo_size_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_bujeo_size_min_other_cov_obs[[4]]$log_lambda),
    rep(NA, nb_proj * nb_years),
    c(ibm_bujeo_summerT_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_bujeo_summerT_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_bujeo_summerT_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_bujeo_summerT_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_bujeo_prevwinterT_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_bujeo_prevwinterT_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_bujeo_prevwinterT_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_bujeo_prevwinterT_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_bujeo_fallR_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_bujeo_fallR_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_bujeo_fallR_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_bujeo_fallR_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_bujeo_prevfallR_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_bujeo_prevfallR_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_bujeo_prevfallR_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_bujeo_prevfallR_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_bujeo_prevwinterR_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_bujeo_prevwinterR_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_bujeo_prevwinterR_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_bujeo_prevwinterR_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_bujeo_dens_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_bujeo_dens_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_bujeo_dens_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_bujeo_dens_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_bujeo_size_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_bujeo_size_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_bujeo_size_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_bujeo_size_max_other_cov_obs[[4]]$log_lambda),
    rep(NA, nb_proj * nb_years))


results_df$lambda[which(results_df$population == "Prisoneros")] = 
  c(c(ibm_prisoneros_summerT_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_prisoneros_summerT_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_prisoneros_summerT_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_prisoneros_summerT_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_prisoneros_prevwinterT_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_prisoneros_prevwinterT_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_prisoneros_prevwinterT_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_prisoneros_prevwinterT_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_prisoneros_fallR_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_prisoneros_fallR_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_prisoneros_fallR_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_prisoneros_fallR_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_prisoneros_prevfallR_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_prisoneros_prevfallR_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_prisoneros_prevfallR_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_prisoneros_prevfallR_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_prisoneros_prevwinterR_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_prisoneros_prevwinterR_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_prisoneros_prevwinterR_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_prisoneros_prevwinterR_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_prisoneros_dens_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_prisoneros_dens_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_prisoneros_dens_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_prisoneros_dens_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_prisoneros_size_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_prisoneros_size_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_prisoneros_size_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_prisoneros_size_min_other_cov_mean[[4]]$log_lambda),
    rep(NA, nb_proj * nb_years),
    c(ibm_prisoneros_summerT_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_prisoneros_summerT_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_prisoneros_summerT_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_prisoneros_summerT_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_prisoneros_prevwinterT_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_prisoneros_prevwinterT_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_prisoneros_prevwinterT_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_prisoneros_prevwinterT_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_prisoneros_fallR_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_prisoneros_fallR_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_prisoneros_fallR_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_prisoneros_fallR_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_prisoneros_prevfallR_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_prisoneros_prevfallR_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_prisoneros_prevfallR_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_prisoneros_prevfallR_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_prisoneros_prevwinterR_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_prisoneros_prevwinterR_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_prisoneros_prevwinterR_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_prisoneros_prevwinterR_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_prisoneros_dens_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_prisoneros_dens_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_prisoneros_dens_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_prisoneros_dens_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_prisoneros_size_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_prisoneros_size_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_prisoneros_size_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_prisoneros_size_max_other_cov_mean[[4]]$log_lambda),
    rep(NA, nb_proj * nb_years),
    c(ibm_prisoneros_summerT_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_prisoneros_summerT_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_prisoneros_summerT_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_prisoneros_summerT_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_prisoneros_prevwinterT_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_prisoneros_prevwinterT_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_prisoneros_prevwinterT_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_prisoneros_prevwinterT_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_prisoneros_fallR_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_prisoneros_fallR_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_prisoneros_fallR_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_prisoneros_fallR_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_prisoneros_prevfallR_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_prisoneros_prevfallR_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_prisoneros_prevfallR_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_prisoneros_prevfallR_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_prisoneros_prevwinterR_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_prisoneros_prevwinterR_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_prisoneros_prevwinterR_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_prisoneros_prevwinterR_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_prisoneros_dens_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_prisoneros_dens_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_prisoneros_dens_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_prisoneros_dens_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_prisoneros_size_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_prisoneros_size_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_prisoneros_size_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_prisoneros_size_min_other_cov_obs[[4]]$log_lambda),
    rep(NA, nb_proj * nb_years),
    c(ibm_prisoneros_summerT_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_prisoneros_summerT_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_prisoneros_summerT_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_prisoneros_summerT_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_prisoneros_prevwinterT_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_prisoneros_prevwinterT_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_prisoneros_prevwinterT_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_prisoneros_prevwinterT_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_prisoneros_fallR_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_prisoneros_fallR_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_prisoneros_fallR_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_prisoneros_fallR_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_prisoneros_prevfallR_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_prisoneros_prevfallR_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_prisoneros_prevfallR_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_prisoneros_prevfallR_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_prisoneros_prevwinterR_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_prisoneros_prevwinterR_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_prisoneros_prevwinterR_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_prisoneros_prevwinterR_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_prisoneros_dens_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_prisoneros_dens_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_prisoneros_dens_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_prisoneros_dens_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_prisoneros_size_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_prisoneros_size_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_prisoneros_size_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_prisoneros_size_max_other_cov_obs[[4]]$log_lambda),
    rep(NA, nb_proj * nb_years))


results_df$lambda[which(results_df$population == "Retin")] = 
  c(c(ibm_retin_summerT_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_retin_summerT_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_retin_summerT_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_retin_summerT_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_retin_prevwinterT_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_retin_prevwinterT_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_retin_prevwinterT_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_retin_prevwinterT_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_retin_fallR_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_retin_fallR_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_retin_fallR_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_retin_fallR_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_retin_prevfallR_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_retin_prevfallR_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_retin_prevfallR_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_retin_prevfallR_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_retin_prevwinterR_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_retin_prevwinterR_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_retin_prevwinterR_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_retin_prevwinterR_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_retin_dens_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_retin_dens_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_retin_dens_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_retin_dens_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_retin_size_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_retin_size_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_retin_size_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_retin_size_min_other_cov_mean[[4]]$log_lambda),
    rep(NA, nb_proj * nb_years),
    c(ibm_retin_summerT_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_retin_summerT_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_retin_summerT_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_retin_summerT_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_retin_prevwinterT_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_retin_prevwinterT_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_retin_prevwinterT_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_retin_prevwinterT_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_retin_fallR_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_retin_fallR_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_retin_fallR_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_retin_fallR_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_retin_prevfallR_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_retin_prevfallR_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_retin_prevfallR_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_retin_prevfallR_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_retin_prevwinterR_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_retin_prevwinterR_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_retin_prevwinterR_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_retin_prevwinterR_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_retin_dens_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_retin_dens_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_retin_dens_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_retin_dens_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_retin_size_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_retin_size_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_retin_size_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_retin_size_max_other_cov_mean[[4]]$log_lambda),
    rep(NA, nb_proj * nb_years),
    c(ibm_retin_summerT_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_retin_summerT_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_retin_summerT_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_retin_summerT_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_retin_prevwinterT_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_retin_prevwinterT_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_retin_prevwinterT_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_retin_prevwinterT_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_retin_fallR_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_retin_fallR_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_retin_fallR_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_retin_fallR_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_retin_prevfallR_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_retin_prevfallR_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_retin_prevfallR_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_retin_prevfallR_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_retin_prevwinterR_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_retin_prevwinterR_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_retin_prevwinterR_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_retin_prevwinterR_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_retin_dens_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_retin_dens_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_retin_dens_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_retin_dens_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_retin_size_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_retin_size_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_retin_size_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_retin_size_min_other_cov_obs[[4]]$log_lambda),
    rep(NA, nb_proj * nb_years),
    c(ibm_retin_summerT_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_retin_summerT_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_retin_summerT_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_retin_summerT_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_retin_prevwinterT_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_retin_prevwinterT_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_retin_prevwinterT_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_retin_prevwinterT_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_retin_fallR_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_retin_fallR_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_retin_fallR_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_retin_fallR_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_retin_prevfallR_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_retin_prevfallR_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_retin_prevfallR_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_retin_prevfallR_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_retin_prevwinterR_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_retin_prevwinterR_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_retin_prevwinterR_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_retin_prevwinterR_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_retin_dens_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_retin_dens_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_retin_dens_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_retin_dens_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_retin_size_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_retin_size_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_retin_size_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_retin_size_max_other_cov_obs[[4]]$log_lambda),
    rep(NA, nb_proj * nb_years))


results_df$lambda[which(results_df$population == "MonteraTorero")] = 
  c(c(ibm_monteratorero_summerT_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_monteratorero_summerT_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_monteratorero_summerT_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_monteratorero_summerT_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_monteratorero_prevwinterT_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_monteratorero_prevwinterT_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_monteratorero_prevwinterT_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_monteratorero_prevwinterT_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_monteratorero_fallR_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_monteratorero_fallR_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_monteratorero_fallR_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_monteratorero_fallR_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_monteratorero_prevfallR_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_monteratorero_prevfallR_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_monteratorero_prevfallR_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_monteratorero_prevfallR_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_monteratorero_prevwinterR_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_monteratorero_prevwinterR_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_monteratorero_prevwinterR_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_monteratorero_prevwinterR_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_monteratorero_dens_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_monteratorero_dens_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_monteratorero_dens_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_monteratorero_dens_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_monteratorero_size_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_monteratorero_size_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_monteratorero_size_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_monteratorero_size_min_other_cov_mean[[4]]$log_lambda),
    rep(NA, nb_proj * nb_years),
    c(ibm_monteratorero_summerT_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_monteratorero_summerT_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_monteratorero_summerT_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_monteratorero_summerT_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_monteratorero_prevwinterT_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_monteratorero_prevwinterT_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_monteratorero_prevwinterT_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_monteratorero_prevwinterT_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_monteratorero_fallR_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_monteratorero_fallR_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_monteratorero_fallR_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_monteratorero_fallR_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_monteratorero_prevfallR_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_monteratorero_prevfallR_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_monteratorero_prevfallR_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_monteratorero_prevfallR_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_monteratorero_prevwinterR_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_monteratorero_prevwinterR_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_monteratorero_prevwinterR_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_monteratorero_prevwinterR_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_monteratorero_dens_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_monteratorero_dens_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_monteratorero_dens_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_monteratorero_dens_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_monteratorero_size_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_monteratorero_size_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_monteratorero_size_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_monteratorero_size_max_other_cov_mean[[4]]$log_lambda),
    rep(NA, nb_proj * nb_years),
    c(ibm_monteratorero_summerT_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_monteratorero_summerT_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_monteratorero_summerT_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_monteratorero_summerT_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_monteratorero_prevwinterT_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_monteratorero_prevwinterT_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_monteratorero_prevwinterT_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_monteratorero_prevwinterT_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_monteratorero_fallR_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_monteratorero_fallR_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_monteratorero_fallR_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_monteratorero_fallR_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_monteratorero_prevfallR_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_monteratorero_prevfallR_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_monteratorero_prevfallR_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_monteratorero_prevfallR_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_monteratorero_prevwinterR_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_monteratorero_prevwinterR_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_monteratorero_prevwinterR_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_monteratorero_prevwinterR_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_monteratorero_dens_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_monteratorero_dens_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_monteratorero_dens_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_monteratorero_dens_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_monteratorero_size_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_monteratorero_size_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_monteratorero_size_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_monteratorero_size_min_other_cov_obs[[4]]$log_lambda),
    rep(NA, nb_proj * nb_years),
    c(ibm_monteratorero_summerT_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_monteratorero_summerT_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_monteratorero_summerT_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_monteratorero_summerT_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_monteratorero_prevwinterT_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_monteratorero_prevwinterT_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_monteratorero_prevwinterT_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_monteratorero_prevwinterT_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_monteratorero_fallR_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_monteratorero_fallR_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_monteratorero_fallR_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_monteratorero_fallR_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_monteratorero_prevfallR_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_monteratorero_prevfallR_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_monteratorero_prevfallR_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_monteratorero_prevfallR_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_monteratorero_prevwinterR_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_monteratorero_prevwinterR_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_monteratorero_prevwinterR_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_monteratorero_prevwinterR_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_monteratorero_dens_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_monteratorero_dens_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_monteratorero_dens_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_monteratorero_dens_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_monteratorero_size_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_monteratorero_size_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_monteratorero_size_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_monteratorero_size_max_other_cov_obs[[4]]$log_lambda),
    rep(NA, nb_proj * nb_years))


results_df$lambda[which(results_df$population == "SCarbDist")] = 
  c(c(ibm_scarbdist_summerT_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_scarbdist_summerT_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_scarbdist_summerT_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_scarbdist_summerT_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_scarbdist_prevwinterT_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_scarbdist_prevwinterT_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_scarbdist_prevwinterT_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_scarbdist_prevwinterT_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_scarbdist_fallR_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_scarbdist_fallR_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_scarbdist_fallR_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_scarbdist_fallR_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_scarbdist_prevfallR_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_scarbdist_prevfallR_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_scarbdist_prevfallR_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_scarbdist_prevfallR_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_scarbdist_prevwinterR_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_scarbdist_prevwinterR_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_scarbdist_prevwinterR_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_scarbdist_prevwinterR_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_scarbdist_dens_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_scarbdist_dens_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_scarbdist_dens_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_scarbdist_dens_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_scarbdist_size_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_scarbdist_size_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_scarbdist_size_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_scarbdist_size_min_other_cov_mean[[4]]$log_lambda),
    rep(NA, nb_proj * nb_years),
    c(ibm_scarbdist_summerT_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_scarbdist_summerT_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_scarbdist_summerT_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_scarbdist_summerT_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_scarbdist_prevwinterT_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_scarbdist_prevwinterT_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_scarbdist_prevwinterT_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_scarbdist_prevwinterT_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_scarbdist_fallR_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_scarbdist_fallR_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_scarbdist_fallR_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_scarbdist_fallR_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_scarbdist_prevfallR_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_scarbdist_prevfallR_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_scarbdist_prevfallR_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_scarbdist_prevfallR_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_scarbdist_prevwinterR_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_scarbdist_prevwinterR_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_scarbdist_prevwinterR_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_scarbdist_prevwinterR_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_scarbdist_dens_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_scarbdist_dens_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_scarbdist_dens_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_scarbdist_dens_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_scarbdist_size_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_scarbdist_size_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_scarbdist_size_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_scarbdist_size_max_other_cov_mean[[4]]$log_lambda),
    rep(NA, nb_proj * nb_years),
    c(ibm_scarbdist_summerT_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_scarbdist_summerT_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_scarbdist_summerT_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_scarbdist_summerT_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_scarbdist_prevwinterT_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_scarbdist_prevwinterT_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_scarbdist_prevwinterT_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_scarbdist_prevwinterT_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_scarbdist_fallR_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_scarbdist_fallR_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_scarbdist_fallR_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_scarbdist_fallR_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_scarbdist_prevfallR_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_scarbdist_prevfallR_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_scarbdist_prevfallR_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_scarbdist_prevfallR_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_scarbdist_prevwinterR_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_scarbdist_prevwinterR_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_scarbdist_prevwinterR_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_scarbdist_prevwinterR_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_scarbdist_dens_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_scarbdist_dens_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_scarbdist_dens_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_scarbdist_dens_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_scarbdist_size_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_scarbdist_size_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_scarbdist_size_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_scarbdist_size_min_other_cov_obs[[4]]$log_lambda),
    rep(NA, nb_proj * nb_years),
    c(ibm_scarbdist_summerT_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_scarbdist_summerT_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_scarbdist_summerT_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_scarbdist_summerT_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_scarbdist_prevwinterT_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_scarbdist_prevwinterT_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_scarbdist_prevwinterT_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_scarbdist_prevwinterT_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_scarbdist_fallR_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_scarbdist_fallR_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_scarbdist_fallR_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_scarbdist_fallR_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_scarbdist_prevfallR_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_scarbdist_prevfallR_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_scarbdist_prevfallR_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_scarbdist_prevfallR_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_scarbdist_prevwinterR_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_scarbdist_prevwinterR_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_scarbdist_prevwinterR_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_scarbdist_prevwinterR_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_scarbdist_dens_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_scarbdist_dens_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_scarbdist_dens_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_scarbdist_dens_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_scarbdist_size_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_scarbdist_size_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_scarbdist_size_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_scarbdist_size_max_other_cov_obs[[4]]$log_lambda),
    rep(NA, nb_proj * nb_years))


results_df$lambda[which(results_df$population == "SierraCarboneraY5")] = 
  c(c(ibm_sierracarboneray5_summerT_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_sierracarboneray5_summerT_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_sierracarboneray5_summerT_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_sierracarboneray5_summerT_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_sierracarboneray5_prevwinterT_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_sierracarboneray5_prevwinterT_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_sierracarboneray5_prevwinterT_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_sierracarboneray5_prevwinterT_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_sierracarboneray5_fallR_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_sierracarboneray5_fallR_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_sierracarboneray5_fallR_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_sierracarboneray5_fallR_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_sierracarboneray5_prevfallR_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_sierracarboneray5_prevfallR_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_sierracarboneray5_prevfallR_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_sierracarboneray5_prevfallR_min_other_cov_mean[[4]]$log_lambda),
    rep(NA, nb_proj * nb_years),
    c(ibm_sierracarboneray5_dens_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_sierracarboneray5_dens_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_sierracarboneray5_dens_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_sierracarboneray5_dens_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_sierracarboneray5_size_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_sierracarboneray5_size_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_sierracarboneray5_size_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_sierracarboneray5_size_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_sierracarboneray5_TSF_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_sierracarboneray5_TSF_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_sierracarboneray5_TSF_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_sierracarboneray5_TSF_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_sierracarboneray5_summerT_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_sierracarboneray5_summerT_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_sierracarboneray5_summerT_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_sierracarboneray5_summerT_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_sierracarboneray5_prevwinterT_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_sierracarboneray5_prevwinterT_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_sierracarboneray5_prevwinterT_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_sierracarboneray5_prevwinterT_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_sierracarboneray5_fallR_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_sierracarboneray5_fallR_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_sierracarboneray5_fallR_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_sierracarboneray5_fallR_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_sierracarboneray5_prevfallR_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_sierracarboneray5_prevfallR_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_sierracarboneray5_prevfallR_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_sierracarboneray5_prevfallR_max_other_cov_mean[[4]]$log_lambda),
    rep(NA, nb_proj * nb_years),
    c(ibm_sierracarboneray5_dens_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_sierracarboneray5_dens_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_sierracarboneray5_dens_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_sierracarboneray5_dens_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_sierracarboneray5_size_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_sierracarboneray5_size_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_sierracarboneray5_size_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_sierracarboneray5_size_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_sierracarboneray5_TSF_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_sierracarboneray5_TSF_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_sierracarboneray5_TSF_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_sierracarboneray5_TSF_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_sierracarboneray5_summerT_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_sierracarboneray5_summerT_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_sierracarboneray5_summerT_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_sierracarboneray5_summerT_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_sierracarboneray5_prevwinterT_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_sierracarboneray5_prevwinterT_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_sierracarboneray5_prevwinterT_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_sierracarboneray5_prevwinterT_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_sierracarboneray5_fallR_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_sierracarboneray5_fallR_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_sierracarboneray5_fallR_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_sierracarboneray5_fallR_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_sierracarboneray5_prevfallR_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_sierracarboneray5_prevfallR_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_sierracarboneray5_prevfallR_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_sierracarboneray5_prevfallR_min_other_cov_obs[[4]]$log_lambda),
    rep(NA, nb_proj * nb_years),
    c(ibm_sierracarboneray5_dens_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_sierracarboneray5_dens_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_sierracarboneray5_dens_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_sierracarboneray5_dens_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_sierracarboneray5_size_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_sierracarboneray5_size_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_sierracarboneray5_size_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_sierracarboneray5_size_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_sierracarboneray5_TSF_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_sierracarboneray5_TSF_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_sierracarboneray5_TSF_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_sierracarboneray5_TSF_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_sierracarboneray5_summerT_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_sierracarboneray5_summerT_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_sierracarboneray5_summerT_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_sierracarboneray5_summerT_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_sierracarboneray5_prevwinterT_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_sierracarboneray5_prevwinterT_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_sierracarboneray5_prevwinterT_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_sierracarboneray5_prevwinterT_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_sierracarboneray5_fallR_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_sierracarboneray5_fallR_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_sierracarboneray5_fallR_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_sierracarboneray5_fallR_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_sierracarboneray5_prevfallR_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_sierracarboneray5_prevfallR_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_sierracarboneray5_prevfallR_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_sierracarboneray5_prevfallR_max_other_cov_obs[[4]]$log_lambda),
    rep(NA, nb_proj * nb_years),
    c(ibm_sierracarboneray5_dens_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_sierracarboneray5_dens_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_sierracarboneray5_dens_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_sierracarboneray5_dens_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_sierracarboneray5_size_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_sierracarboneray5_size_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_sierracarboneray5_size_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_sierracarboneray5_size_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_sierracarboneray5_TSF_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_sierracarboneray5_TSF_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_sierracarboneray5_TSF_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_sierracarboneray5_TSF_max_other_cov_obs[[4]]$log_lambda))

results_df$lambda[which(results_df$population == "SierraRetinY5")] = 
  c(c(ibm_sierraretiny5_summerT_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_sierraretiny5_summerT_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_sierraretiny5_summerT_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_sierraretiny5_summerT_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_sierraretiny5_prevwinterT_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_sierraretiny5_prevwinterT_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_sierraretiny5_prevwinterT_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_sierraretiny5_prevwinterT_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_sierraretiny5_fallR_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_sierraretiny5_fallR_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_sierraretiny5_fallR_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_sierraretiny5_fallR_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_sierraretiny5_prevfallR_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_sierraretiny5_prevfallR_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_sierraretiny5_prevfallR_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_sierraretiny5_prevfallR_min_other_cov_mean[[4]]$log_lambda),
    rep(NA, nb_proj * nb_years),
    c(ibm_sierraretiny5_dens_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_sierraretiny5_dens_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_sierraretiny5_dens_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_sierraretiny5_dens_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_sierraretiny5_size_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_sierraretiny5_size_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_sierraretiny5_size_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_sierraretiny5_size_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_sierraretiny5_TSF_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_sierraretiny5_TSF_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_sierraretiny5_TSF_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_sierraretiny5_TSF_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_sierraretiny5_summerT_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_sierraretiny5_summerT_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_sierraretiny5_summerT_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_sierraretiny5_summerT_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_sierraretiny5_prevwinterT_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_sierraretiny5_prevwinterT_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_sierraretiny5_prevwinterT_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_sierraretiny5_prevwinterT_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_sierraretiny5_fallR_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_sierraretiny5_fallR_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_sierraretiny5_fallR_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_sierraretiny5_fallR_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_sierraretiny5_prevfallR_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_sierraretiny5_prevfallR_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_sierraretiny5_prevfallR_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_sierraretiny5_prevfallR_max_other_cov_mean[[4]]$log_lambda),
    rep(NA, nb_proj * nb_years),
    c(ibm_sierraretiny5_dens_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_sierraretiny5_dens_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_sierraretiny5_dens_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_sierraretiny5_dens_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_sierraretiny5_size_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_sierraretiny5_size_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_sierraretiny5_size_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_sierraretiny5_size_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_sierraretiny5_TSF_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_sierraretiny5_TSF_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_sierraretiny5_TSF_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_sierraretiny5_TSF_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_sierraretiny5_summerT_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_sierraretiny5_summerT_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_sierraretiny5_summerT_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_sierraretiny5_summerT_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_sierraretiny5_prevwinterT_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_sierraretiny5_prevwinterT_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_sierraretiny5_prevwinterT_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_sierraretiny5_prevwinterT_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_sierraretiny5_fallR_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_sierraretiny5_fallR_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_sierraretiny5_fallR_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_sierraretiny5_fallR_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_sierraretiny5_prevfallR_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_sierraretiny5_prevfallR_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_sierraretiny5_prevfallR_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_sierraretiny5_prevfallR_min_other_cov_obs[[4]]$log_lambda),
    rep(NA, nb_proj * nb_years),
    c(ibm_sierraretiny5_dens_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_sierraretiny5_dens_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_sierraretiny5_dens_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_sierraretiny5_dens_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_sierraretiny5_size_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_sierraretiny5_size_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_sierraretiny5_size_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_sierraretiny5_size_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_sierraretiny5_TSF_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_sierraretiny5_TSF_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_sierraretiny5_TSF_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_sierraretiny5_TSF_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_sierraretiny5_summerT_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_sierraretiny5_summerT_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_sierraretiny5_summerT_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_sierraretiny5_summerT_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_sierraretiny5_prevwinterT_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_sierraretiny5_prevwinterT_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_sierraretiny5_prevwinterT_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_sierraretiny5_prevwinterT_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_sierraretiny5_fallR_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_sierraretiny5_fallR_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_sierraretiny5_fallR_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_sierraretiny5_fallR_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_sierraretiny5_prevfallR_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_sierraretiny5_prevfallR_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_sierraretiny5_prevfallR_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_sierraretiny5_prevfallR_max_other_cov_obs[[4]]$log_lambda),
    rep(NA, nb_proj * nb_years),
    c(ibm_sierraretiny5_dens_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_sierraretiny5_dens_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_sierraretiny5_dens_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_sierraretiny5_dens_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_sierraretiny5_size_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_sierraretiny5_size_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_sierraretiny5_size_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_sierraretiny5_size_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_sierraretiny5_TSF_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_sierraretiny5_TSF_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_sierraretiny5_TSF_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_sierraretiny5_TSF_max_other_cov_obs[[4]]$log_lambda))

results_df$lambda[which(results_df$population == "Vertedero")] = 
  c(c(ibm_vertedero_summerT_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_vertedero_summerT_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_vertedero_summerT_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_vertedero_summerT_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_vertedero_prevwinterT_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_vertedero_prevwinterT_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_vertedero_prevwinterT_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_vertedero_prevwinterT_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_vertedero_fallR_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_vertedero_fallR_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_vertedero_fallR_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_vertedero_fallR_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_vertedero_prevfallR_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_vertedero_prevfallR_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_vertedero_prevfallR_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_vertedero_prevfallR_min_other_cov_mean[[4]]$log_lambda),
    rep(NA, nb_proj * nb_years),
    c(ibm_vertedero_dens_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_vertedero_dens_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_vertedero_dens_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_vertedero_dens_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_vertedero_size_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_vertedero_size_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_vertedero_size_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_vertedero_size_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_vertedero_TSF_min_other_cov_mean[[1]]$log_lambda),
    c(ibm_vertedero_TSF_min_other_cov_mean[[2]]$log_lambda),
    c(ibm_vertedero_TSF_min_other_cov_mean[[3]]$log_lambda),
    c(ibm_vertedero_TSF_min_other_cov_mean[[4]]$log_lambda),
    c(ibm_vertedero_summerT_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_vertedero_summerT_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_vertedero_summerT_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_vertedero_summerT_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_vertedero_prevwinterT_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_vertedero_prevwinterT_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_vertedero_prevwinterT_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_vertedero_prevwinterT_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_vertedero_fallR_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_vertedero_fallR_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_vertedero_fallR_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_vertedero_fallR_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_vertedero_prevfallR_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_vertedero_prevfallR_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_vertedero_prevfallR_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_vertedero_prevfallR_max_other_cov_mean[[4]]$log_lambda),
    rep(NA, nb_proj * nb_years),
    c(ibm_vertedero_dens_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_vertedero_dens_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_vertedero_dens_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_vertedero_dens_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_vertedero_size_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_vertedero_size_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_vertedero_size_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_vertedero_size_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_vertedero_TSF_max_other_cov_mean[[1]]$log_lambda),
    c(ibm_vertedero_TSF_max_other_cov_mean[[2]]$log_lambda),
    c(ibm_vertedero_TSF_max_other_cov_mean[[3]]$log_lambda),
    c(ibm_vertedero_TSF_max_other_cov_mean[[4]]$log_lambda),
    c(ibm_vertedero_summerT_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_vertedero_summerT_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_vertedero_summerT_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_vertedero_summerT_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_vertedero_prevwinterT_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_vertedero_prevwinterT_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_vertedero_prevwinterT_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_vertedero_prevwinterT_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_vertedero_fallR_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_vertedero_fallR_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_vertedero_fallR_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_vertedero_fallR_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_vertedero_prevfallR_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_vertedero_prevfallR_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_vertedero_prevfallR_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_vertedero_prevfallR_min_other_cov_obs[[4]]$log_lambda),
    rep(NA, nb_proj * nb_years),
    c(ibm_vertedero_dens_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_vertedero_dens_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_vertedero_dens_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_vertedero_dens_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_vertedero_size_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_vertedero_size_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_vertedero_size_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_vertedero_size_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_vertedero_TSF_min_other_cov_obs[[1]]$log_lambda),
    c(ibm_vertedero_TSF_min_other_cov_obs[[2]]$log_lambda),
    c(ibm_vertedero_TSF_min_other_cov_obs[[3]]$log_lambda),
    c(ibm_vertedero_TSF_min_other_cov_obs[[4]]$log_lambda),
    c(ibm_vertedero_summerT_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_vertedero_summerT_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_vertedero_summerT_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_vertedero_summerT_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_vertedero_prevwinterT_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_vertedero_prevwinterT_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_vertedero_prevwinterT_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_vertedero_prevwinterT_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_vertedero_fallR_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_vertedero_fallR_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_vertedero_fallR_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_vertedero_fallR_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_vertedero_prevfallR_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_vertedero_prevfallR_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_vertedero_prevfallR_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_vertedero_prevfallR_max_other_cov_obs[[4]]$log_lambda),
    rep(NA, nb_proj * nb_years),
    c(ibm_vertedero_dens_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_vertedero_dens_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_vertedero_dens_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_vertedero_dens_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_vertedero_size_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_vertedero_size_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_vertedero_size_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_vertedero_size_max_other_cov_obs[[4]]$log_lambda),
    c(ibm_vertedero_TSF_max_other_cov_obs[[1]]$log_lambda),
    c(ibm_vertedero_TSF_max_other_cov_obs[[2]]$log_lambda),
    c(ibm_vertedero_TSF_max_other_cov_obs[[3]]$log_lambda),
    c(ibm_vertedero_TSF_max_other_cov_obs[[4]]$log_lambda))


# Transform log lambdas into lambdas and set infinite values to 0. 
# Infinite values are caused by the lack of aboveground individuals (the projections
# continue because there are still seeds in the seedbank).
results_df$lambda = exp(results_df$lambda)
results_df$lambda[which(is.nan(results_df$lambda))] = 0


# Get mean lambda per projection for each scenario
results_df = aggregate(lambda ~ population + focal_cov + focal_min_max + other_mean_obs + projection, 
                       data = results_df[which(!is.infinite(results_df$lambda)), ],
                       mean, na.rm = T)

# Format data
results_df$focal_full = NA
results_df$focal_full[which(results_df$focal_cov == "summerT")] = "Next summer mean max.\ndaily temperature"
results_df$focal_full[which(results_df$focal_cov == "prevwinterT")] = "Previous winter mean max.\ndaily temperature"
results_df$focal_full[which(results_df$focal_cov == "fallR")] = "Next fall cumulative\nrainfall"
results_df$focal_full[which(results_df$focal_cov == "prevfallR")] = "Previous fall cumulative\nrainfall"
results_df$focal_full[which(results_df$focal_cov == "prevwinterR")] = "Previous winter cumulative\nrainfall"
results_df$focal_full[which(results_df$focal_cov == "dens")] = "Aboveground density of\nlarge individuals"
results_df$focal_full[which(results_df$focal_cov == "size")] = "Size"
results_df$focal_full[which(results_df$focal_cov == "TSF")] = "Time Since Fire"

results_df$scenario = paste0("Focal covariate = ", results_df$focal_full, " (", results_df$focal_min_max, " value) ",
                            "\nOther covariates = ", results_df$other_mean_obs, " value")
results_df$focal_scenario = paste0(results_df$focal_full, " = ", results_df$focal_min_max, " value")
results_df$other_scenario = paste0(results_df$other_mean_obs, " value")




###########################################################################
#
# 3. Plotting results ----
#
###########################################################################

png(filename = "DewyPine_Lambdas_Covariation.png", 
     width = 25,
     height = 20,
     units = "cm",
     bg = "white",
     res = 600)

ggplot(results_df[which(!is.infinite(results_df$lambda)), ], aes(x = focal_scenario, y = lambda, fill = other_scenario)) +
  geom_boxplot(alpha = 0.6) +
  stat_summary(fun = mean, position = position_dodge(0.75)) +
  scale_fill_manual(name = "Other covariates",
                      values = viridis(2, begin = 0.4, end = 0.8, option = "B"),
                      labels = c("Mean value", "Observed value at\nfocal covariate value")) +
  xlab("Focal covariate value") +
  ylab("Population growth rate (\u03BB)") +
  theme_minimal() +
  theme(axis.text = element_text(size = 10, colour = "black"),
        axis.text.x = element_text(angle = 90, hjust = 1),
        axis.title = element_text(size = 12, colour = "black"),
        axis.title.x = element_text(margin = margin(t = 15)),
        axis.title.y = element_text(margin = margin(r = 15)),
        legend.title = element_text(size = 12, colour = "black"),
        legend.text = element_text(size = 10, colour = "black"))

write.csv(results_df, "Covariation_results_df.csv", row.names = F)

dev.off()
